### ISSUE TITLE
test IFTTT

### ISSUE THREAD

**Issue by shimoe** [agrirobo/cancer#1]
githubのissueをslackに通知するテスト

**Comment by shimoe** [comment]
出来たので閉じます

**Comment by forno** [comment]
それうちがこっそり設定してなかったっけ？ｗ

**Comment by shimoe** [comment]
どこに？
issueだけの通知とかしてたっけ
それとも単にissueがなかっただけか

まぁ西田研用のテストだから

**Comment by forno** [comment]
OK. ちなみに登録しておいたのは昔 shimoeと作ったARCのslack当てだわ．

**Comment by forno** [comment]
SlackとGithubの連携だと，デフォルトでコミット，Issue, Pull-requestを内容までとかOpen-Closeだけとかの制御が細やかに効くので，そちらを利用するように変更しました．

**Comment by forno** [comment]
この設定は agrirobo/cancer と agrirobo/arcsys2 に対して行いました．
設定内容についてはslackのapps&integrationsからgithubを検索して確認してくださいまし．
